name: Coverage
run-name: Coverage for ${{ github.sha }}
on: [push]

jobs:
  coverage:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./UnitTests
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Display Python version for testing purposes
        run: python -c "import sys; print(sys.version)"
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "requirements.txt"
      - name: Run unittests with pytest
        run: python run_all_tests.py
      - name: Coverage Badge.
        uses: tj-actions/coverage-badge-py@v2
        working-directory: .
      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v13
        id: verify-changed-files
        with:
          files: coverage.svg
      - name: Commit files
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git pull
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add coverage.svg
          git commit -m "Updated coverage.svg"
          git push
