name: Coverage
run-name: Coverage for ${{ github.sha }}
on: [push]

jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      os: ubuntu-latest
      python-version: '3.11'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ python-version }}
      - name: Display Python version for testing purposes
        run: python -c "import sys; print(sys.version)"
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "requirements.txt"
      - name: Run unittests with pytest
        run: python UnitTests/run_all_tests.py
      - name: Coverage Badge
        uses: tj-actions/coverage-badge-py@v2
